import { ColorSchemeScript } from '@mantine/core';
import { MantineShared } from '@graditude-client-monorepo/mantine-shared';

export const metadata = {
  title: 'Welcome to graditude-marketing',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineShared>{children}</MantineShared>
      </body>
    </html>
  );
}
